# Generated by Django 5.1 on 2024-08-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
